package pdg.Controller;

public enum Action {
	GENERATE, CONFIRM, GAME_START, ZOOM_IN, ZOOM_OUT, GAME_SETTINGS, RESULTS_ZOOM_OUT, RESULTS_ZOOM_IN, BACK_TO_VIEW, CIRCLE, HIERARCHICAL, ORGANIC, VIEW_RESULT_NETWORK
}
